---
- name: Create local key and deploy it
  hosts: mcr-alpha
  remote_user: null
  gather_facts: false
  roles:
    - localKey

- name: Install python
  hosts: mcr-alpha
  remote_user: null
  gather_facts: false
  roles:
    - python

- name: Setup pi
  hosts: mcr-alpha
  remote_user: alarm
  vars:
    ansible_host_key_checking: false
    ansible_ssh_host_key_checking: false
  roles:
    - initial

- name: Setup kiosk
  hosts: mcr-alpha
  remote_user: odroid
  vars:
    ansible_host_key_checking: false
    ansible_ssh_host_key_checking: false
  roles:
    - kiosk
