all:
  children:
    cnc:
      vars:
        ansible_ssh_private_key_file: "{{inventory_dir}}/sshKey"
        ansible_ssh_public_key_file: "{{inventory_dir}}/sshKey.pub"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      children:
        cncServer:
          hosts:
            mcr-alpha:
              ansible_host: mcr-alpha.lan
              barrierCommand: 'barriers --config /home/odroid/barrierConfiguration --name mcr-alpha --disable-crypto -f'
              dashboardUrl: 'http://roonadan.lan/d/1i0gquEmz/turris?orgId=1&refresh=30s'
        cncClient:
          vars:
            barrierCommand: 'barrierc --disable-crypto -f mcr-alpha'
          hosts:
            mcr-gamma:
              ansible_host: mcr-gamma.lan
              dashboardUrl: 'http://roonadan.lan/d/hfvfaCyik/mqtt?orgId=1&refresh=30s'
            mcr-delta:
              ansible_host: mcr-delta.lan
              dashboardUrl: 'http://roonadan.lan/d/tI2qaTEiz/odroid?orgId=1&refresh=30s'
            mcr-beta:
              ansible_host: mcr-beta.lan
              dashboardUrl: 'http://roonadan.lan/d/OsA71lsiz/spaceapi?orgId=1&refresh=30s'
